from handler import Handler
from mainpage import MainPage
from newpost import NewPost
from blogfront import BlogFront
from postpage import PostPage
from signup import Signup
from register import Register
from login import Login
from logout import Logout
from like import Like
from postedit import PostEdit
from postdelete import PostDelete
from commentedit import CommentEdit
from commentdelete import CommentDelete